version: '3.2'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
    driver: "bridge"